---
resources:
- name: reports
  type: git
  source:
    uri: git@github.com:aldrinb/aws-reports.git
    branch: master
    private_key: {{aws_reports_deploy_key}}
    ignore_paths: [ ci/* ]

- name: volumes-available-data-s3
  type: s3
  source:
    bucket: {{reports_bucket}}
    regexp: v1/volumes-available-(.*).json
    access_key_id: {{reporting_aws_access_key_id}}
    secret_access_key: {{reporting_aws_secret_access_key}}
    region_name: &reporting-aws-region eu-central-1

jobs:
- name: create-volume-data
  serial: true
  plan:
  - get: reports
    trigger: true
  - task: describe-volumes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
      inputs:
        - name: reports
      outputs:
        - name: data
      params:
        AWS_ACCESS_KEY_ID: {{reporting_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{reporting_aws_secret_access_key}}
        AWS_DEFAULT_REGION: *reporting-aws-region
      run:
        path: reports/ec2-volumes.sh
        args: [ "data" ]
  - put: volumes-available-data-s3
    params:
      file: data/volumes-available-*.json
      acl: private

- name: create-volume-reports
  plan:
  - get: reports
  - get: volumes-available-data-s3
    trigger: true
  - task: count-available-volumes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
      inputs:
        - name: volumes-available-data-s3
        - name: reports
      run:
        path: reports/ec2-volume-count.sh
        args: [ "volumes-available-data-s3" ]
